# Generated by Django 6.0.2 on 2026-03-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='proficiency_level',
        ),
    ]
